#!/usr/bin/env python3
"""
scripts/verify_repo_reference_integrity.py

Generalizes the exact bug found in the ytclfr / theytclfr case on 2026-09-18:

  core/wiki/projects/ytclfr.md has repo_reference: https://github.com/MuzammilCk/ytclfr
  (pushed_at 2026-03-07, 193 days dormant per core/progress/github-telemetry.json)

  ...while the real active work is at https://github.com/MuzammilCk/theytclfr
  (pushed_at 2026-08-27, 20 days ago, activity_status "recent_30d"), which
  sync_github_tracker.py's own REPO_ALIASES table already correctly maps to
  matched_vault_slug "ytclfr".

Root cause: sync_github_tracker.py matches EVERY telemetry-side repo to a
vault slug independently -- it never checks whether two repos landed on the
same slug, and it never writes back to the wiki page. compile_portfolio.py
then reads repo_reference from the wiki page's frontmatter completely
uncritically (by design -- see its own docstring) and bakes it straight into
the public portfolio.json. So a stale repo_reference isn't just wrong in the
vault, it silently ships to the live public site on the next scheduled sync.

This script closes the gap by cross-checking every project's chosen
repo_reference against what telemetry actually knows about that slug, and
flagging it when telemetry's own data says a different, more active repo
should be canonical. It does NOT auto-edit wiki frontmatter -- matching
`/decide` and `/debrief`'s existing "propose, don't silently rewrite" pattern,
a human confirms which repo is actually the successor before repo_reference
changes (two repos can share a slug's *name* without being the same project).

Usage:
    python scripts/verify_repo_reference_integrity.py            # report + exit code
Importable:
    from verify_repo_reference_integrity import check_repo_references
    (see APPLY.md for wiring this into verify_boundaries.py's main())
"""

import os
import sys
import json
import re

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from frontmatter_utils import parse_frontmatter_and_body  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
PROJECTS_DIR = os.path.join(ROOT, "core", "wiki", "projects")
TELEMETRY_FILE = os.path.join(ROOT, "core", "progress", "github-telemetry.json")

# Lower rank = more trustworthy as "the" canonical repo for a slug.
ACTIVITY_RANK = {"active_7d": 0, "recent_30d": 1, "unknown": 2, "dormant": 3}


def _repo_name_from_url(url):
    if not url:
        return None
    return url.rstrip("/").split("/")[-1].lower()


def check_repo_references(fail_on_flagship_mismatch=True):
    """Returns (errors: list[str], warnings: list[str])."""
    errors, warnings = [], []

    if not os.path.exists(TELEMETRY_FILE):
        warnings.append(
            f"{os.path.relpath(TELEMETRY_FILE, ROOT)} not found -- skipping repo_reference "
            f"integrity check. This file is only refreshed by sync_github_tracker.py, which "
            f"needs the gh CLI locally; it is NOT regenerated by live-sync.yml in CI."
        )
        return errors, warnings

    with open(TELEMETRY_FILE, "r", encoding="utf-8") as handle:
        telemetry = json.load(handle)
    repos = telemetry.get("repositories", {})

    # Build slug -> [ (repo_name, repo_info), ... ] reverse index
    slug_to_repos = {}
    for repo_name, info in repos.items():
        slug = info.get("matched_vault_slug")
        if slug:
            slug_to_repos.setdefault(slug, []).append((repo_name, info))

    if not os.path.exists(PROJECTS_DIR):
        return errors, warnings

    for fname in sorted(os.listdir(PROJECTS_DIR)):
        if not fname.endswith(".md") or fname.endswith("-decisions.md") or fname == "index.md":
            continue
        path = os.path.join(PROJECTS_DIR, fname)
        with open(path, "r", encoding="utf-8") as handle:
            fm, _ = parse_frontmatter_and_body(handle.read())

        slug = fname[:-3]
        repo_ref = fm.get("repo_reference")
        matches = slug_to_repos.get(slug, [])
        if not matches:
            continue  # untracked by telemetry -- not this script's problem

        matches_sorted = sorted(matches, key=lambda kv: ACTIVITY_RANK.get(kv[1].get("activity_status"), 9))
        best_name, best_info = matches_sorted[0]
        chosen_name = _repo_name_from_url(repo_ref)

        chosen_info = next((info for name, info in matches if name.lower() == chosen_name), None)

        location = f"core/wiki/projects/{fname}"
        is_flagship_export = (str(fm.get("tier", "")).lower() == "flagship" and str(fm.get("export", "")).lower() == "true")

        if chosen_info is None:
            msg = (
                f"[{location}] repo_reference '{repo_ref}' does not match any GitHub repo "
                f"telemetry maps to slug '{slug}'. Known matches for this slug: "
                f"{', '.join(n for n, _ in matches)}."
            )
            (errors if is_flagship_export else warnings).append(msg)
            continue

        if len(matches) > 1 and chosen_name != best_name:
            chosen_days = chosen_info.get("days_since_push")
            best_days = best_info.get("days_since_push")
            # Only escalate to a real problem when the gap is large enough that
            # this isn't just "both repos are basically equally fresh".
            gap_is_real = (
                chosen_info.get("activity_status") == "dormant"
                and best_info.get("activity_status") in ("active_7d", "recent_30d")
            )
            msg = (
                f"[{location}] repo_reference points at '{chosen_name}' "
                f"({chosen_days} days since push, {chosen_info.get('activity_status')}), but "
                f"'{best_name}' ({best_days} days since push, {best_info.get('activity_status')}) "
                f"also maps to slug '{slug}' and is more recently active. If '{best_name}' is the "
                f"real successor repo, update repo_reference via /decide -- don't hand-edit "
                f"silently, in case these are actually two unrelated repos that happen to share "
                f"a matched slug."
            )
            if gap_is_real and is_flagship_export and fail_on_flagship_mismatch:
                errors.append(msg)
            else:
                warnings.append(msg)

    return errors, warnings


def main():
    print("[Verifying repo_reference integrity against github-telemetry.json...]")
    errors, warnings = check_repo_references()
    for w in warnings:
        print(f"  [WARN] {w}")
    for e in errors:
        print(f"  [ERROR] {e}", file=sys.stderr)
    if errors:
        print(f"[FAIL] {len(errors)} repo_reference integrity error(s).", file=sys.stderr)
        sys.exit(1)
    print(f"[OK] repo_reference check passed ({len(warnings)} warning(s)).")


if __name__ == "__main__":
    main()
